---
- name: Configurar servidor DNS amb BIND
  hosts: all
  become: yes
  vars:
    domini: "exemple.com"
    zone_file: "/etc/bind/db.{{ domini }}"
  tasks:

    - name: Actualitzar els paquets
      apt:
        update_cache: yes

    - name: Instal·lar BIND
      apt:
        name: bind9
        state: present

    - name: Crear el fitxer de zona si no existeix
      template:
        src: templates/FitxerDeZona.j2
        dest: "{{ zone_file }}"
        owner: root
        group: bind
        mode: '0644'

    - name: Afegir declaració de zona a named.conf.local
      blockinfile:
        path: /etc/bind/named.conf.local
        block: |
          {% include 'templates/DeclaracioZona.j2' %}
        state: present
        insertafter: EOF

    - name: Reiniciar i habilitar BIND per aplicar els canvis
      service:
        name: bind9
        state: restarted
        enabled: yes

    - name: Comprovar que el servei bind9 està en marxa
      command: systemctl status bind9
      register: bind_status
      changed_when: false

    - name: Mostrar estat de bind9
      debug:
        msg: "{{ bind_status.stdout_lines }}"

    - name: Comprovar resolució DNS del domini
      command: dig @192.168.11.5 {{ domini }}
      register: dig_result
      changed_when: false

    - name: Mostrar resultat de la consulta DNS
      debug:
        msg: "{{ dig_result.stdout_lines }}"