---
- name: Create VirtualHost with HTTPS for Apache2
  hosts: "{{ WEB }}"
  become: true
  vars:
    zone: "{{ zone }}"
    DNS: "{{ DNS }}"
  tasks:
    - name: Install Apache2 and OpenSSL
      apt:
        name:
          - apache2
          - openssl
        state: present
        update_cache: yes

    - name: Enable necessary Apache modules
      command: a2enmod "{{ item }}"
      loop:
        - rewrite
        - ssl
      notify: Restart Apache2

    - name: Create SSL private key
      command: openssl genpkey -algorithm RSA -out /etc/ssl/private/{{ zone }}.key
      args:
        creates: /etc/ssl/private/{{ zone }}.key

    - name: Create SSL certificate signing request (CSR)
      command: >
        openssl req -new -key /etc/ssl/private/{{ zone }}.key -out /etc/ssl/certs/{{ zone }}.csr
        -subj "/C=ES/ST=Baleares/L=Manacor/O={{ zone }}/OU={{ zone }}/CN={{ zone }}/emailAddress={{ zone }}"
      args:
        creates: /etc/ssl/certs/{{ zone }}.csr

    - name: Self-sign SSL certificate
      command: openssl x509 -req -in /etc/ssl/certs/{{ zone }}.csr -signkey /etc/ssl/private/{{ zone }}.key -out /etc/ssl/certs/{{ zone }}.crt
      args:
        creates: /etc/ssl/certs/{{ zone }}.crt

    - name: Set permissions for SSL private key
      file:
        path: "/etc/ssl/private/{{ zone }}.key"
        mode: '0600'
        owner: root
        group: root

    - name: Create HTTP and HTTPS virtualhost configuration file
      template:
        src: ../templates/virtualhost.j2
        dest: "/etc/apache2/sites-available/{{ zone }}.conf"
        mode: '0644'

    - name: Enable the new site
      command: a2ensite "{{ zone }}.conf"
      notify: Restart Apache2

  handlers:
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted